name: Release Helm charts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/Chart.yaml'

jobs:
 release-charts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - tyk-oss
          - tyk-stack
          - tyk-control-plane
          - tyk-data-plane

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.5.3

      - name: Read Helm Chart version
        id: chart-version
        run: echo "version=$(awk '/^version:/ {print $2}' ${{ matrix.chart }}/Chart.yaml)" >> "$GITHUB_OUTPUT"

      - name: Helm Chart package file name
        id: file-name
        run: |
          echo "fileName=$(basename ${{ matrix.chart }})-v2.1.1-alpha.tgz"
          echo "fileName=$(basename ${{ matrix.chart }})-v2.1.1-alpha.tgz" >> "$GITHUB_OUTPUT"

      - name: Update dependencies
        run: helm dependency update ${{ matrix.chart }}

      - name: Package Helm Chart
        run: helm package ${{ matrix.chart }} --version v2.1.1-alpha

      - name: Push Helm Chart
        uses: cloudsmith-io/action@v0.5.2
        with:
         api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
         command: "push"
         format: "helm"
         owner: "tyk"
         repo: "helm"
         file: "${{ steps.file-name.outputs.fileName }}"
